---
title: "Untitled"
author: "Niklas"
date: '2024-03-09'
output: html_document
---
# Info
This script works along the `RDA_Vegan.Rmd` or the `RDA_Short.Rmd` script and is only for customising the RDA Plot.


```{r}

# Define the dataset you want to analyse

Data <- All_RDA
# plot.new()

## extract % explained by the first 2 axes
perc <- round(100*(summary(Data)$cont$importance[2, 1:2]), 2)

## extract scores - these are coordinates in the RDA space
sc_si <- scores(Data, display="sites", choices=c(1,2), scaling=1)
sc_sp <- scores(Data, display="species", choices=c(1,2), scaling=1)
sc_bp <- scores(Data, display="bp", choices=c(1, 2), scaling=1)

## Custom triplot, step by step

# png("Faunal_Remains_RDA.png", width=100, height=220.51, res=300, units="cm", bg="white")


# Set up a blank plot with scaling, axes, and labels
plot(Data,
     scaling = 2, # set scaling type 
     type = "none", # this excludes the plotting of any points from the results
     frame = FALSE,
     # set axis limits
     xlim = c(-1,1), 
     ylim = c(-1,1),
     # label the plot (title, and axes)
     main = "Botanical Remains RDA",
     xlab = paste0("RDA1 (", perc[1], "%)"), 
     ylab = paste0("RDA2 (", perc[2], "%)") 
)
# add points for site scores
points(sc_si, 
       pch = 21, # set shape (here, circle with a fill colour)
       col = "white", # outline colour
       bg = "#223466ff", # fill colour
       cex = 1.2) # size
# add points for species scores
points(sc_sp, 
       pch = 22, # set shape (here, square with a fill colour)
       col = "black",
       bg = "#fdb21aff", 
       cex = 1.2)
# add text labels for species abbreviations
text(sc_sp + c(0.03, 0.09), # adjust text coordinates to avoid overlap with points 
     labels = rownames(sc_sp), 
     col = "grey40", 
     font = 2, # bold
     cex = 1)
# add arrows for effects of the expanatory variables
arrows(0,0, # start them from (0,0)
       sc_bp[,1]*2, sc_bp[,2]*2, # end them at the score value
       col = "#e84148ff", 
       lwd = 3)
# add text labels for arrows
text(x = sc_bp[,1] * 2.4, # adjust text coordinate to avoid overlap with arrow tip
     y = sc_bp[,2] * 2.4, 
     labels = rownames(sc_bp), 
     col = "#e84148ff", 
     cex = 2, 
     font = 2,
     adj = c(1, 0.5)) # Centered horizontally and vertically


# dev.off()


```

# ggplot
## FAUNA
### Showing sites by period
```{r}
Data <- All_RDA
# plot.new()

## extract % explained by the first 2 axes
perc <- round(100*(summary(Data)$cont$importance[2, 1:2]), 2)
# Assuming Data is an rda result, sc_si are site scores, sc_sp are species scores, and sc_bp are biplot scores

# scaling = 0: scaling for species scores (species-focused)
# scaling = 1: scaling for site scores (site-focused)
# scaling = 2: Hill's scaling (equalize the variance of scores)
scaling <-  0

# Extract scores
site_scores <- scores(Data, display="sites", choices=c(1,2), scaling=scaling)
species_scores <- scores(Data, display="species", choices=c(1,2), scaling=scaling)
biplot_scores <- scores(Data, display="bp", choices=c(1, 2), scaling=scaling)


# Combining and reshaping the data frames using tidyr for a more concise approach
df_sites <- data.frame(site_scores[, 1:2], Type = "Site", Labels = rownames(site_scores))
df_species <- data.frame(species_scores[, 1:2], Type = "Species", Labels = rownames(species_scores))
df_biplot <- data.frame(RDA1 = biplot_scores[, 1] * 2, RDA2 = biplot_scores[, 2] * 2, Type = "Biplot", Labels = rownames(biplot_scores))

# Use bind_rows from dplyr to combine, since tidyr is more about reshaping
df_combined <- dplyr::bind_rows(df_sites, df_species) %>%
  rename(RDA1 = 1, RDA2 = 2) %>% 
  left_join(D18O %>% rename(Labels=trenchunit) %>% select(Labels,chronology),by="Labels")# Ensure the column names are consistent

###### make hull
site_data <- subset(df_combined, Type == "Site")

# Split data by 'chronology'
split_data <- split(site_data, site_data$chronology)

# Function to calculate convex hull and return a data frame with the hull points
calc_hull_df <- function(df) {
  hull_indices <- chull(df$RDA1, df$RDA2)
  hull_df <- df[hull_indices, ]
  return(hull_df)
}

# Apply the function to each group
hulls <- lapply(split_data, calc_hull_df)

# Combine the hull data frames, add a row to close the polygon
hulls_df <- do.call(rbind, lapply(names(hulls), function(name) {
  rbind(hulls[[name]], hulls[[name]][1, ])
}))
####



# Plotting
ggplot() +
  geom_blank(aes(x = RDA1, y = RDA2), data = df_combined) +
  # geom_polygon(data = hulls_df %>% na.omit(), aes(x = RDA1, y = RDA2, fill = chronology, group = chronology), alpha = 0.2) +
  geom_point(data = df_combined[df_combined$Type == "Site", ], aes(x = RDA1, y = RDA2,col=chronology),
             #fill = "#223466ff", 
             size = 4) +
  scale_fill_manual(values = chron_colours) + 
  scale_colour_manual(values = chron_colours) + 
  # geom_point(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2), shape = 22, color = "black", fill = "#fdb21aff", size = 4,alpha=0.2) +
  # geom_text(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2, label = Labels), hjust = 1.1, vjust = 1.1, color = "grey40", fontface = "bold", size = 3.5,alpha=1) +
  geom_segment(data = df_biplot, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), arrow = arrow(type = "closed"), color = "#e84148ff", linewidth = 1) +
  geom_text(data = df_biplot, aes(x = RDA1, y = RDA2, label = rownames(df_biplot)), color = "#e84148ff", size = 6, fontface = "bold", hjust = 0.1, vjust = 1.91) +
  # scale_x_continuous(limits = c(-2, 2)) +
  # scale_y_continuous(limits = c(-1, 1)) +
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), title = "Faunal Remains RDA") +
  theme_cowplot()
ggsave(filename = here("plots","RDA-Fauna-Sites.png"),width=30,height=20,units = "cm")

```
### Showing species related to periods
```{r}
Data <- All_RDA
# plot.new()

## extract % explained by the first 2 axes
perc <- round(100*(summary(Data)$cont$importance[2, 1:2]), 2)
# Assuming Data is an rda result, sc_si are site scores, sc_sp are species scores, and sc_bp are biplot scores

# scaling = 0: scaling for species scores (species-focused)
# scaling = 1: scaling for site scores (site-focused)
# scaling = 2: Hill's scaling (equalize the variance of scores)
scaling <-  0

# Extract scores
site_scores <- scores(Data, display="sites", choices=c(1,2), scaling=scaling)
species_scores <- scores(Data, display="species", choices=c(1,2), scaling=scaling)
biplot_scores <- scores(Data, display="bp", choices=c(1, 2), scaling=scaling)


# Combining and reshaping the data frames using tidyr for a more concise approach
df_sites <- data.frame(site_scores[, 1:2], Type = "Site", Labels = rownames(site_scores))
df_species <- data.frame(species_scores[, 1:2], Type = "Species", Labels = rownames(species_scores))
df_biplot <- data.frame(RDA1 = biplot_scores[, 1] * 2, RDA2 = biplot_scores[, 2] * 2, Type = "Biplot", Labels = rownames(biplot_scores)) 

# Use bind_rows from dplyr to combine, since tidyr is more about reshaping
df_combined <- dplyr::bind_rows(df_sites, df_species) %>%
  rename(RDA1 = 1, RDA2 = 2) %>% 
  left_join(D18O %>% rename(Labels=trenchunit) %>% select(Labels,chronology),by="Labels") %>% # Ensure the column names are consistent
   mutate(Labels = case_when(
    Labels == "fishes_non_tuna" ~ "Fishes not Tuna",
    Labels == "tuna" ~ "Tuna",
    Labels == "birds" ~ "Birds",
    Labels == "small_mammal" ~ "Small Mammal",
    Labels == "hare" ~ "Hare",
    Labels == "medium_mammal" ~ "Medium Mammal",
    Labels == "equid" ~ "Equid",
    Labels == "cervidae" ~ "Cervidae",
    Labels == "bos" ~ "Bos",
    Labels == "sus_scrofa" ~ "Wildboar",
    Labels == "caprines" ~ "Caprines",
    Labels == "small_ungulate" ~ "Small Ungulate",
    Labels == "med_ungulate" ~ "Med Ungulate",
    Labels == "large_ungulate" ~ "Large Ungulate",
    Labels == "small_carnivore" ~ "Small Carnivore",
    Labels == "domestic_dog" ~ "Domestic Dog",
    Labels == "cattle" ~ "Cattle",
    Labels == "pig" ~ "Pig",
    Labels == "molluscs" ~ "Molluscs",
    TRUE ~ Labels # Default case to keep original values where no change is needed
  ))

# Plotting
ggplot() +
  geom_blank(aes(x = RDA1, y = RDA2), data = df_combined) +
   geom_polygon(data = hulls_df %>% na.omit(), aes(x = RDA1, y = RDA2, fill = chronology, group = chronology), alpha = 0.2) +
  geom_point(data = df_combined[df_combined$Type == "Site", ], aes(x = RDA1, y = RDA2,col=chronology),alpha=0.2,   size = 4) +
    scale_fill_manual(values = chron_colours) + 
    scale_colour_manual(values = chron_colours) + 
  # geom_point(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2), shape = 22, color = "black", fill = "black", size = 4,alpha=1) +
  # geom_text(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2, label = Labels), hjust = 1.1, vjust = 1.1, color = "black", fontface = "bold", size = 3.5,alpha=1) +
  geom_segment(data = df_biplot, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), arrow = arrow(type = "closed"), color = "#e84148ff", linewidth = 1) +
  geom_text(data = df_biplot, aes(x = RDA1, y = RDA2, label = rownames(df_biplot)), color = "#e84148ff", size = 6, fontface = "bold", hjust = 0.1, vjust = 1.91) +
annotate("text", x = -0.8, y = 0.6, label = "Initial Neolithic\n(7000-6500 cal BC)",color = "#7D3C98", fontface = "bold", alpha=0.9)+
annotate("text", x = 0.55, y = 0, label = "Early Neolithic\n(6500-5800 cal BC)",color = "#9B30FF", fontface = "bold", alpha=0.7)+
annotate("text", x = -0.9, y = 0.2, label = "Middle Neolithic\n(5800-5000 cal BC)",color = "#74C365", fontface = "bold", alpha=0.9)+
  # scale_x_continuous(limits = c(-2, 2)) +
  # scale_y_continuous(limits = c(-1, 1)) +
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), title = "Faunal Remains RDA") +
  theme_cowplot()

ggsave(filename = here("plots","RDA-Fauna-Periods.png"),width=30,height=20,units = "cm")

```

## Flora
### Showing sites by period
```{r}
Data <- All_RDA
# plot.new()

## extract % explained by the first 2 axes
perc <- round(100*(summary(Data)$cont$importance[2, 1:2]), 2)
# Assuming Data is an rda result, sc_si are site scores, sc_sp are species scores, and sc_bp are biplot scores

# scaling = 0: scaling for species scores (species-focused)
# scaling = 1: scaling for site scores (site-focused)
# scaling = 2: Hill's scaling (equalize the variance of scores)
scaling <-  0

# Extract scores
site_scores <- scores(Data, display="sites", choices=c(1,2), scaling=scaling)
species_scores <- scores(Data, display="species", choices=c(1,2), scaling=scaling)
biplot_scores <- scores(Data, display="bp", choices=c(1, 2), scaling=scaling)


# Combining and reshaping the data frames using tidyr for a more concise approach
df_sites <- data.frame(site_scores[, 1:2], Type = "Site", Labels = rownames(site_scores))
df_species <- data.frame(species_scores[, 1:2], Type = "Species", Labels = rownames(species_scores))
df_biplot <- data.frame(RDA1 = biplot_scores[, 1] * 2, RDA2 = biplot_scores[, 2] * 2, Type = "Biplot", Labels = rownames(biplot_scores))

# Use bind_rows from dplyr to combine, since tidyr is more about reshaping
df_combined <- dplyr::bind_rows(df_sites, df_species) %>%
  rename(RDA1 = 1, RDA2 = 2) %>% 
  left_join(D18O %>% rename(Labels=trenchunit) %>% select(Labels,chronology),by="Labels")# Ensure the column names are consistent

# Plotting
ggplot() +
  geom_blank(aes(x = RDA1, y = RDA2), data = df_combined) +
  geom_point(data = df_combined[df_combined$Type == "Site", ], aes(x = RDA1, y = RDA2,fill=chronology), shape = 21, color = "white", 
             #fill = "#223466ff", 
             size = 4) +
    scale_fill_manual(values = chron_colours) + 
  geom_point(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2), shape = 22, color = "black", fill = "#fdb21aff", size = 4,alpha=0.2) +
  geom_text(data = df_combined[df_combined$Type == "Site", ], aes(x = RDA1, y = RDA2, label = Labels), hjust = 1.1, vjust = 1.1, color = "grey40", fontface = "bold", size = 3.5,alpha=0.2) +
  geom_segment(data = df_biplot, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), arrow = arrow(type = "closed"), color = "#e84148ff", linewidth = 1) +
  geom_text(data = df_biplot, aes(x = RDA1, y = RDA2, label = rownames(df_biplot)), color = "#e84148ff", size = 6, fontface = "bold", hjust = 0.1, vjust = 1.91) +
  # scale_x_continuous(limits = c(-2, 2)) +
  # scale_y_continuous(limits = c(-1, 1)) +
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), title = "Botanical Remains RDA") +
  theme_cowplot()

```
### Showing species related to periods
```{r}
Data <- All_RDA
# plot.new()

## extract % explained by the first 2 axes
perc <- round(100*(summary(Data)$cont$importance[2, 1:2]), 2)
# Assuming Data is an rda result, sc_si are site scores, sc_sp are species scores, and sc_bp are biplot scores

# scaling = 0: scaling for species scores (species-focused)
# scaling = 1: scaling for site scores (site-focused)
# scaling = 2: Hill's scaling (equalize the variance of scores)
scaling <-  0

# Extract scores
site_scores <- scores(Data, display="sites", choices=c(1,2), scaling=scaling)
species_scores <- scores(Data, display="species", choices=c(1,2), scaling=scaling)
biplot_scores <- scores(Data, display="bp", choices=c(1, 2), scaling=scaling)


# Combining and reshaping the data frames using tidyr for a more concise approach
df_sites <- data.frame(site_scores[, 1:2], Type = "Site", Labels = rownames(site_scores))
df_species <- data.frame(species_scores[, 1:2], Type = "Species", Labels = rownames(species_scores))
df_biplot <- data.frame(RDA1 = biplot_scores[, 1] * 2, RDA2 = biplot_scores[, 2] * 2, Type = "Biplot", Labels = rownames(biplot_scores))

# Use bind_rows from dplyr to combine, since tidyr is more about reshaping
df_combined <- dplyr::bind_rows(df_sites, df_species) %>%
  rename(RDA1 = 1, RDA2 = 2) %>% 
  left_join(D18O %>% rename(Labels=trenchunit) %>% select(Labels,chronology),by="Labels")# Ensure the column names are consistent

# Plotting
ggplot() +
  geom_blank(aes(x = RDA1, y = RDA2), data = df_combined) +
  geom_point(data = df_combined[df_combined$Type == "Site", ], aes(x = RDA1, y = RDA2,fill=chronology), shape = 21, color = "white", 
             #fill = "#223466ff", 
             size = 4,alpha=0.2) +
    scale_fill_manual(values = chron_colours) + 
  geom_point(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2), shape = 22, color = "black", fill = "#fdb21aff", size = 4,alpha=1) +
  geom_text(data = df_combined[df_combined$Type == "Species", ], aes(x = RDA1, y = RDA2, label = Labels), hjust = 1.1, vjust = 1.1, color = "grey40", fontface = "bold", size = 3.5,alpha=1) +
  geom_segment(data = df_biplot, aes(x = 0, y = 0, xend = RDA1, yend = RDA2), arrow = arrow(type = "closed"), color = "#e84148ff", linewidth = 1) +
  geom_text(data = df_biplot, aes(x = RDA1, y = RDA2, label = rownames(df_biplot)), color = "#e84148ff", size = 6, fontface = "bold", hjust = 0.1, vjust = 1.91) +
  # scale_x_continuous(limits = c(-2, 2)) +
  # scale_y_continuous(limits = c(-1, 1)) +
  labs(x = paste0("RDA1 (", perc[1], "%)"), y = paste0("RDA2 (", perc[2], "%)"), title = "Botanical Remains RDA") +
  theme_cowplot()

```
